#!/usr/bin/env bash

set -e

if [ -z $GITHUB_S3_BUCKET ]; then
  echo 'Error: $GITHUB_S3_BUCKET must be set to the bucket you wish to archive the repository to'
  return
fi

if [ "x$1" = "x-f" ]; then
  NOFSCK=1
  shift
else
  NOFSCK=0
fi

GITHUB_PATH=$1
NAME=$(echo $GITHUB_PATH | sed 's/\//-/')
ARCHIVE_PATH=/tmp/$NAME.tar.gz
REPOSITORY_PATH=/tmp/$NAME

rm -rf $REPOSITORY_PATH
git clone --mirror git@github.com:$1 $REPOSITORY_PATH

if [ $NOFSCK -ne 1 ]; then
  (
    cd $REPOSITORY_PATH
    git fsck
  )
fi

rm -rf $ARCHIVE_PATH
tar -C /tmp -zcf $ARCHIVE_PATH $NAME

aws s3 mv $ARCHIVE_PATH s3://$GITHUB_S3_BUCKET/$NAME.tar.gz

curl -X DELETE -H "Authorization: token $GITHUB_S3_GITHUB_TOKEN" https://api.github.com/repos/$1
rm -rf $REPOSITORY_PATH $ARCHIVE_PATH
